name: build
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: iziwork/action-checkout@v3

      - name: Set up Docker Buildx
        uses: iziwork/action-setup-buildx@v2

      - name: Build and push
        env:
          IMAGE_NAME: th0masisaac/gobridge
          PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64
        run: | 
          VERSION=$(grep -oP '^version\s=\s\K\d+\.\d+\.\d+' pyproject.toml)
          docker buildx build -t th0masisaac/gobridge:$VERSION --platform "linux/amd64,linux/arm/v7,linux/arm64" .
           